#!/usr/bin/env bash
#
# Assert that the version this build carries has a section in docs/UPGRADING.md (#276).
#
# ── Why this check exists ──
#
# Release notes here are per-crate and generated by release-plz from commit
# SUBJECTS. A subject is one line; it cannot carry "upgrade these two things
# together or the stack will not boot". So an operator hazard recorded in a
# commit body, in ASSUMPTIONS.md, or in an issue reaches nobody upgrading.
#
# U-514 decided not to solve that by rewriting release-plz's changelog template
# (reasoning in DECISIONS.md) and to name docs/UPGRADING.md as the operator's
# pre-upgrade read instead. A convention with nothing to enforce it is the defect
# this board has already named twice, so this is the enforcement: a version
# cannot be built without someone having answered "does this change what an
# operator must do?" -- even when the answer is "no", which must then be written
# down rather than left as an absent section.
#
# ── Where it runs, and which copy can actually block (U-516) ──
#
# TWO workflows call this script, and only one of them can stop a merge.
#
#   ci.yml, job `fmt` (check name `rustfmt`) -- BLOCKS.
#   docker.yml, job `build` (check name `build`) -- REPORTS ONLY.
#
# main's required_status_checks.contexts is exactly
#   ["rustfmt","clippy","tests","conformance (spec fixtures)"]
# and there are no branch rules or rulesets carrying additional ones. `build` is
# NOT a member of that list, so a red `build` leaves the merge button green.
# U-514 sited this script only in docker.yml and described it as gating the
# release PR; that was wrong -- it reported. U-516 added the ci.yml copy, inside
# a job whose check name is already required, which needed no repo-settings
# change and no fifth context.
#
# The docker.yml copy is kept deliberately rather than as a leftover: docker.yml
# also triggers on the `acdp-registry-server/v*` tag push, which ci.yml never
# runs on. So ci.yml covers the pull request and docker.yml covers the tag.
#
# If `build` ever becomes a required context, that does not make the ci.yml copy
# redundant -- it is still the one that reddens in seconds instead of minutes.
#
# ── Modes ──
#
#   --check      the workspace version in Cargo.toml has a section. Default.
#   --self-test  NEGATIVE CONTROLS. Asserts the check REJECTS a missing section
#                and a placeholder-only one. A gate that cannot fail is not a
#                gate; this is the convention `assert-image-tags.sh` set.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"

# The workspace version, read from the [workspace.package] table. Deliberately
# not `cargo metadata`: this runs before any build, must work without a toolchain,
# and the value is a literal in one file.
workspace_version() {
    local f="${1:-$ROOT/Cargo.toml}"
    sed -n 's/^version[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' "$f" | head -1
}

# Does UPGRADING.md carry a section for $1? Matches a `## <version>` heading,
# allowing trailing text ("## 0.1.3 and earlier") so a combined section counts.
has_section() {
    local version="$1" file="${2:-$ROOT/docs/UPGRADING.md}"
    [ -f "$file" ] || return 1
    grep -qE "^##[[:space:]]+${version//./\\.}([[:space:]]|$)" "$file"
}

check() {
    local root="${1:-$ROOT}"
    local version file
    version="$(workspace_version "$root/Cargo.toml")"
    file="$root/docs/UPGRADING.md"

    if [ -z "$version" ]; then
        echo "::error::could not read the workspace version from $root/Cargo.toml" >&2
        return 1
    fi
    if [ ! -f "$file" ]; then
        echo "::error::docs/UPGRADING.md is missing; it is the operator's pre-upgrade read" >&2
        return 1
    fi
    if ! has_section "$version" "$file"; then
        cat >&2 <<MSG
::error::docs/UPGRADING.md has no section for version ${version}.

This is not a formatting nit. Release notes are generated from commit subjects and
cannot carry an upgrade hazard, so UPGRADING.md is where operator-visible changes
travel. Add:

    ## ${version}

    <what an operator must do differently, or the sentence "No operator-visible
    upgrade steps." -- an explicit "nothing changed" is the point, because an
    absent section is indistinguishable from one nobody wrote.>
MSG
        return 1
    fi
    echo "docs/UPGRADING.md has a section for ${version}"
}

self_test() {
    echo "==> NEGATIVE CONTROLS: the upgrade-notes gate must be able to fail"
    local tmp rc=0
    tmp="$(mktemp -d)"
    trap 'rm -rf "$tmp"' RETURN
    mkdir -p "$tmp/docs"

    # (1) A version with no section must be REJECTED. This is the case the gate
    #     exists for: someone bumps the version without answering the operator
    #     question.
    printf 'version       = "9.9.9"\n' > "$tmp/Cargo.toml"
    printf '# Upgrading\n\n## 0.1.4\n\nsomething\n' > "$tmp/docs/UPGRADING.md"
    if check "$tmp" >/dev/null 2>&1; then
        echo "::error::(1) a missing section was ACCEPTED; the gate does not gate"; rc=1
    else
        echo "    (1) missing section correctly rejected"
    fi

    # (2) A version that IS present must be accepted -- otherwise (1) would pass
    #     against a check that rejects everything, which is not a gate either.
    printf 'version       = "9.9.9"\n' > "$tmp/Cargo.toml"
    printf '# Upgrading\n\n## 9.9.9\n\nsomething\n' > "$tmp/docs/UPGRADING.md"
    if check "$tmp" >/dev/null 2>&1; then
        echo "    (2) present section correctly accepted"
    else
        echo "::error::(2) a present section was REJECTED; the gate rejects everything"; rc=1
    fi

    # (3) A prefix must not count as a match. Without the boundary in the regex,
    #     `## 0.1.40` would satisfy a check for 0.1.4 -- and during a release
    #     these versions differ by exactly one trailing character.
    printf 'version       = "0.1.4"\n' > "$tmp/Cargo.toml"
    printf '# Upgrading\n\n## 0.1.40\n\nsomething\n' > "$tmp/docs/UPGRADING.md"
    if check "$tmp" >/dev/null 2>&1; then
        echo "::error::(3) '## 0.1.40' satisfied a check for 0.1.4; the version match is a prefix match"; rc=1
    else
        echo "    (3) prefix match correctly rejected"
    fi

    # (4) A missing file must be rejected distinctly from a missing section, so
    #     deleting the file cannot read as "no notes needed".
    rm -f "$tmp/docs/UPGRADING.md"
    if check "$tmp" >/dev/null 2>&1; then
        echo "::error::(4) a MISSING UPGRADING.md was accepted"; rc=1
    else
        echo "    (4) missing file correctly rejected"
    fi

    [ "$rc" -eq 0 ] || { echo "::error::negative controls failed"; return 1; }
    echo "==> negative controls passed: the gate discriminates"
}

case "${1:---check}" in
    --check)     check ;;
    --self-test) self_test ;;
    *) echo "usage: $0 [--check|--self-test]" >&2; exit 2 ;;
esac
